# Dockerfile.backend
# Use the official Python image from the Docker Hub
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY server/requirements.txt /code/
RUN pip install -r requirements.txt

# Copy project
COPY server /code/

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
