# Generated by Django 4.2.9 on 2024-06-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('credentials', 'credentials'), ('google', 'google'), ('apple', 'apple')], default='credentials', max_length=100),
        ),
    ]
