# Generated by Django 4.2.9 on 2024-06-16 10:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+23491234567', max_length=20, region=None, verbose_name='Phone number'),
        ),
    ]
