# Generated by Django 4.0 on 2024-06-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_preference',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=100),
        ),
    ]
