# Generated by Django 4.2.9 on 2024-06-16 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gft', '0003_box_receiver_phone_alter_box_box_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='box_limit',
            field=models.IntegerField(default=0, help_text='Maximum number of gift boxes the company can manage'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='Owner of the company', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
