# Generated by Django 4.0 on 2024-06-17 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gft', '0004_alter_company_box_limit_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='last_opened',
            field=models.DateTimeField(blank=True, help_text='Date when the gift box was last opened', null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the gift box can be opened'),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='groups',
            field=models.ManyToManyField(help_text='Groups associated with the API key', related_name='api_keys', to='gft.PermissionGroup', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='permissionsmodel',
            name='groups',
            field=models.ManyToManyField(help_text='Groups associated with the permission', related_name='permissions', to='gft.PermissionGroup', verbose_name='Groups'),
        ),
    ]
