# Generated by Django 4.2 on 2024-06-18 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gft', '0005_alter_box_last_opened_alter_box_open_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Company who owns the gift box', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gift',
            name='open_date',
            field=models.DateTimeField(help_text='Date when the mini box can be opened'),
        ),
    ]
