# Generated by Django 4.2 on 2024-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gft', '0007_boxcategory_created_at_boxcategory_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='qr_code_v',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='qr_code_v',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='header_image',
            field=models.CharField(blank=True, help_text='Header image for the campaign', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='header_image',
            field=models.CharField(blank=True, help_text='Header image for the company', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, help_text='Logo of the company', null=True),
        ),
    ]
